spring.application.name: protobuf

# default is 9090
spring.grpc.server.port: 9090
# spring.grpc.client.default-channel.address: static://localhost:9090
spring.grpc.client.channels.local.address: 0.0.0.0:9090
